# Uncomment the next line to define a global platform for your project
platform :ios, '14.0' # Capacitor default is 13.0, adjust if needed

target 'App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for App
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'

  # Add any other Capacitor plugins here
  # pod 'CapacitorCommunityCamera', :path => '../../node_modules/@capacitor-community/camera'

end